name: GiveAll
main: fernanACM\GiveAll\GiveAll
version: 1.0.0
api: 5.3.0
author: fernanACM
website: https://github.com/fernanACM
description: Give items to all players on your server. Only for PocketMine-MP 5.0

permissions:
  giveall.cmd.acm:
    default: op
  giveall.edit.acm:
    default: op
  giveall.send.acm:
    default: op